// Invented starting state: who owns what and what they wrote.
// Format: 'PATH': [text, style, wallet index, times taken, extras]
// Style words: colors (lime orange pink purple red green yellow blue muted gradient),
// hl = lime highlight, b i s u = bold italic strike underline, up = uppercase,
// box = boxed, xs sm lg xl = size. Slots not listed here start unclaimed.

export const WALLETS = [
  '7xKq…9fPa', '4mLs…2bRz', '8pTe…1qNc', '3vWb…6dHu', '9GhR…tY4e', 'Bq2N…mX8k',
  '5sPd…Lw3j', 'Cz7V…aE1r', '@mossdad', '@loafmaxi', '@pixelnun', '2kFj…Qp9s', 'HuT3…vN6c', '6rYo…8bMd',
];

export const SEED = {
  'TOPBAR.LOGO': ['', '', 8, 7, { image: 'icon' }],
  'TOPBAR.WORDMARK': ['NOT A LANDING PAGE', 'up', 8, 9],

  'STRIP.BG': ['', '', 3, 1, { bg: 'default' }],
  'STRIP.1': ['KEVIN FROM ACCOUNTING OWES ME 3 SOL.', 'pink b up', 0, 4],
  'STRIP.2': ['this strip pays my rent (it does not)', 'hl', 1, 2],
  'STRIP.3': ['@LOAFMAXI 3 WEEKS', 'yellow b up', 9, 3],
  'STRIP.5': ['gm to everyone except whoever took my last slot', 'muted', 2, 1],
  'STRIP.6': ['HOLDING', 'hl b up', 5, 2],
  'STRIP.7': ['$LOAF season', 'orange b', 9, 1],

  'NAV.1': ['$MOSS', 'hl b', 8, 6],
  'NAV.2': ['', '', 10, 3, { image: 'avatar' }],
  'NAV.3': ['$NAPCOIN', 'hl b', 4, 5],
  'NAV.4': ['wen moon', 'muted', 6, 2],
  'NAV.5': ['WHO WANTS SOME $SOL? 🤑', 'box up', 7, 4],
  'NAV.6': ['$LOAF 🍞', 'hl b', 9, 3],
  'NAV.7': ['here since tues', 'hl', 1, 2],
  'NAV.8': ['$YAWN', 'hl b', 3, 4],
  'NAV.9': ['', '', 11, 2, { image: 'icon' }],
  'NAV.10': ['Connect Wallet', 'box', 12, 5],
  'NAV.11': ['i paid for this', 'purple i', 2, 1],

  'HERO.EYEBROW': ['I BOUGHT THIS AT 3AM', 'muted up', 0, 3],
  'HERO.TAG': ['SOLD OUT (NOT REALLY)', 'hl xs up', 4, 2],
  'HERO.HEADLINE': ['Your ad here. {views} page views per 7d rolling.', 'b', 8, 11, { rent: 0.004 }],
  'HERO.STRIKE': ['a boring website', 'hl s', 5, 2],
  'HERO.BUTTON': ['PRESS HERE', 'box b', 6, 4],
  'HERO.CHIP': ['proud owner of nothing', 'hl', 13, 1],
  'HERO.SMALL': ['HOLDING $TICKER SINCE BLOCK 1', 'lime xs up', 7, 2],

  'BAND.BG': ['', '', 3, 1, { bg: 'default' }],
  'BAND.TITLE': ['PUT YOUR PROJECT IN THIS BAND!', 'green b up', 1, 3, { rent: 0.0008 }],
  'BAND.TILE1': ['', '', 10, 2, { image: 'avatar' }],
  'BAND.TILE2': ['', '', 10, 2, { image: 'avatar' }],
  'BAND.TILE3': ['', '', 10, 3, { image: 'avatar' }],
  'BAND.TILE4': ['', '', 2, 1, { image: 'logo', word: 'NorthPine' }],
  'BAND.TILE5': ['', '', 10, 2, { image: 'avatar' }],
  'BAND.TILE6': ['', '', 11, 4, { image: 'avatar' }],

  'TESTIMONIALS.KICKER': ['🟠🟠🟠 MY DOG RUNS THIS WALLET', 'orange b up', 7, 2],
  'TESTIMONIALS.DISPLAY': ['$SMOL WILL HIT 1B BY FRIDAY', 'gradient b lg up', 4, 6],
  'TESTIMONIALS.1.ICON': ['', '', 0, 1, { image: 'icon' }],
  'TESTIMONIALS.1.NAME': ['Moss Club TVL passes 40k SOL', 'b', 0, 2],
  'TESTIMONIALS.1.BODY': ['Stake on moss.club and grab $MOSS today.\n\nmoss.club/stake\n\nnot financial advice, financial vibes.', 'muted', 0, 2],
  'TESTIMONIALS.2.ICON': ['', '', 8, 2, { image: 'avatar' }],
  'TESTIMONIALS.2.NAME': ['mossdad', 'b', 8, 3],
  'TESTIMONIALS.2.BODY': ['day 40 of owning this card. my wife asked what i do all day. i said i defend a testimonial. she did not ask again.\n\nanyway $MOSS is up.', 'muted', 8, 3],
  'TESTIMONIALS.3.BODY': ['You can buy this testimonial and say whatever you want about us.', 'muted', 3, 1],
  'TESTIMONIALS.4.ICON': ['', '', 5, 1, { image: 'icon' }],
  'TESTIMONIALS.4.NAME': ['bread is a lifestyle', 'b', 5, 1],

  'SHOWCASE.KICKER': ['BUYABLE SECTION', 'muted xs up', 6, 1],
  'SHOWCASE.LIST1': ['This bullet costs more than my car.', 'hl', 6, 3],
  'SHOWCASE.LIST2': ['$WAGMI $WAGMI $WAGMI', 'hl b', 12, 2],
  'SHOWCASE.LIST3': ['7xKq…9fPa', 'hl b sm', 0, 1],
  'SHOWCASE.LIST4': ['Also mine', '', 6, 1],
  'SHOWCASE.LIST5': ['OUTBID', 'red b i up', 13, 2],
  'SHOWCASE.BOXED': ['LO-FI BEATS TO BUY SLOTS TO', 'red box up', 2, 2],
  'SHOWCASE.IMAGE': ['', '', 7, 5, { image: 'poster', word: 'NapBot', sub: 'SLEEP-ALERT WALLET TRACKER' }],
  'SHOWCASE.LONG': ['GRANDMA JUNE\u2019S JAM \u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022 SINCE 1987 \u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022 apricot, fig and one experimental flavour we don\u2019t talk about \u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022 my grandson set this up for me and I do not know how to change it back. hello to everyone at the bingo hall.', 'hl b', 11, 2],
  'SHOWCASE.RENT.TITLE': ['THIS BLOCK IS FOR RENT', 'hl xs up', 9, 3],
  'SHOWCASE.RENT.BODY': ['dm @loafmaxi for rental info', 'b lg', 9, 3],
  'SHOWCASE.RENT.P1': ['1 day = 2,500 – 25,000 $TICKER', '', 9, 1],
  'SHOWCASE.RENT.P2': ['3 days = 6,000 – 60,000 $TICKER', '', 9, 1],
  'SHOWCASE.RENT.P3': ['7 days = 14,000 – 140,000 $TICKER', '', 9, 1],
  'SHOWCASE.RENT.DM': ['DM HERE', 'box b up', 9, 1],

  'STATS.BG': ['', '', 3, 1, { bg: 'default' }],
  'STATS.1.VALUE': ['{slots}', 'b', 1, 2],
  'STATS.1.CAPTION': ['BUYABLE ELEMENTS', 'muted xs up', 1, 1],
  'STATS.2.VALUE': ['$GEMS 💎💎', 'b', 12, 4],
  'STATS.2.CAPTION': ['DIAMOND HANDS, PAPER NAPKINS', 'hl xs up', 12, 1],
  'STATS.3.VALUE': ['CARBS ARE A CURRENCY', 'b up', 9, 5],
  'STATS.3.CAPTION': ['LOAF GANG ASSEMBLE', 'green xs up', 9, 1],
  'STATS.4.VALUE': ['🤑', '', 4, 2],
  'STATS.4.CAPTION': ['PRICE GOES UP, SLEEP GOES DOWN', 'muted xs up', 4, 1],

  'FEATURES.ARROW': ['→ [ A dashboard for people who check charts in the shower ]', 'green b', 5, 2],
  'FEATURES.1.TITLE': ['LOAFMAXI IS BACK', 'pink b up', 9, 2],
  'FEATURES.1.ICON': ['', '', 9, 1, { image: 'icon' }],
  'FEATURES.1.NAME': ['BREAD', 'lime i b up', 9, 1],
  'FEATURES.1.SUB': ['BREADBOARD.FUN', 'muted xs up', 9, 1],
  'FEATURES.2.TITLE': ['Owned by a raccoon 🦝', 'hl b', 3, 3],
  'FEATURES.2.ICON': ['', '', 3, 1, { image: 'avatar' }],
  'FEATURES.2.NAME': ['He has no roadmap. Neither do we.', '', 3, 1],
  'FEATURES.2.SUB': ['RENT this spot ❤️', 'muted', 3, 1],
  'FEATURES.3.ICON': ['', '', 6, 1, { image: 'icon' }],
  'FEATURES.3.NAME': ['NAME GOES HERE', 'b up', 6, 1],
  'FEATURES.3.SUB': ['$QUACK', 'muted', 6, 1],
  'FEATURES.4.TITLE': ['Touch grass 🌱 then buy', 'lg', 2, 2],
  'FEATURES.4.ICON': ['', '', 2, 1, { image: 'avatar' }],
  'FEATURES.4.NAME': ['SPONSORED BY MY MOM', 'b xs up', 2, 1],
  'FEATURES.4.SUB': ['SNOOZE.CLUB', 'muted xs up', 2, 1],
  'FEATURES.5.NAME': ['ANOTHER NAME, CHEAP', 'b xs up', 11, 1],
  'FEATURES.5.SUB': ['LOOK AT IT', 'muted xs up', 11, 1],
  'FEATURES.6.TITLE': ['Hi Mom', 'lg', 13, 2],
  'FEATURES.6.ICON': ['', '', 13, 1, { image: 'icon' }],
  'FEATURES.6.NAME': ['bought this for the lols', 'i', 13, 1],

  'PRICING.KICKER': ['it’s not a coin, it’s a lifestyle', 'orange b', 7, 2],
  'PRICING.1.NAME': ['Buy this tier name', 'b', 1, 1],
  'PRICING.1.PRICE': ['Free* (*not free)', 'b', 1, 3],
  'PRICING.1.BLURB': ['Buy this blurb and describe whatever you like', 'muted', 1, 1],
  'PRICING.1.LINE1': ['Pineapple belongs on pizza.', 'purple b u', 13, 2],
  'PRICING.1.LINE2': ['Also mine', '', 1, 1],
  'PRICING.1.LINE3': ['SEND BREAD PICS', 'b up', 4, 2],
  'PRICING.1.BUTTON': ['DO NOT PRESS', 'box xs up', 5, 1],
  'PRICING.2.NAME': ['$BUCKETS', 'b up', 12, 2],
  'PRICING.2.PRICE': ['Kevin still owes me', 'b', 0, 4],
  'PRICING.2.BLURB': ['Taking this blurb makes me richer, so please do', 'muted', 0, 1],
  'PRICING.2.LINE1': ['Buy this feature line', '', 0, 1],
  'PRICING.2.LINE2': ['Taking offers', '', 0, 1],
  'PRICING.2.LINE3': ['And this one', '', 0, 1],
  'PRICING.2.BUTTON': ['SMASH THIS BUTTON', 'b up', 0, 2],
  'PRICING.3.NAME': ['Snack Break Capital', 'orange b', 6, 2],
  'PRICING.3.PRICE': ['Chillin’ 🧊', 'b', 6, 3],
  'PRICING.3.BLURB': ['Three bullets, one price, one button, all for sale', 'muted', 6, 1],
  'PRICING.3.LINE1': ['Buy this feature line', '', 6, 1],
  'PRICING.3.LINE2': ['Also mine', '', 6, 1],
  'PRICING.3.BUTTON': ['LAST BUTTON STANDING', 'box xs up', 6, 1],

  'LOGOS.BG': ['', '', 3, 1, { bg: 'default' }],
  'LOGOS.1': ['', '', 8, 2, { image: 'logo', word: 'MOSS' }],
  'LOGOS.2': ['', '', 12, 1, { image: 'logo', word: 'gemz' }],
  'LOGOS.4': ['', '', 13, 1, { image: 'logo', word: 'YAWN' }],

  'FAQ.KICKER': ['A BIG EXCHANGE WILL BUY THIS SOON (COPE)', 'orange xs up', 3, 1],
  'FAQ.1.QUESTION': ['I WILL NEVER SELL THIS SLOT 🙌', 'b lg up', 3, 4],
  'FAQ.1.ANSWER': ['award-winning slot (self-awarded)', 'purple b', 7, 2],
  'FAQ.2.QUESTION': ['Buy $TICKER and tell your cat 😻', 'hl b lg', 4, 3],
  'FAQ.2.ANSWER': ['THIS ANSWER WAS TAKEN TWICE TODAY', 'blue b up', 2, 2],
  'FAQ.3.QUESTION': ['CHAPTER ONE: mossdad wakes up, checks his slots, goes back to sleep 🫡🫡', 'hl b', 8, 2],
  'FAQ.4.QUESTION': ['Hey @pixelnun, how is the cat?', 'hl b', 10, 1],
  'FAQ.4.ANSWER': ['THE TICKER IS $TICKER', 'red b up', 1, 3],
  'FAQ.5.QUESTION': ['sunnysidesocks.shop', 'orange', 11, 1],
  'FAQ.5.ANSWER': ['Sunny Side Socks are hand-knit, machine washable and made for long nights in front of charts. Every pair comes with a tiny note. Use code SLOT for 10% off.\n\nsunnysidesocks.shop\n\n🧦🧦🧦🧦🧦🧦🧦🧦', 'orange', 11, 2],

  'AD.DISPLAY': ['SPINNY.WIN', 'gradient b up', 5, 3],
  'AD.LINK': ['https://spinny.win/', 'purple b', 5, 1, { url: 'https://example.com/' }],
  'AD.BUTTON': ['SPIN SPIN SPIN', 'red box xs up', 5, 1],

  'FOOTER.BG': ['', '', 3, 1, { bg: 'default' }],
  'FOOTER.1.1': ['TURTLES > TOKENS', 'b up', 13, 1],
  'FOOTER.1.2': ['$YAWN', 'hl b', 3, 2],
  'FOOTER.1.3': ['ICON ON CLEARANCE', 'muted xs up box', 3, 1],
  'FOOTER.2.1': ['snailcoin', 'b', 4, 1],
  'FOOTER.2.2': ['Buy this link', 'muted', 4, 1],
  'FOOTER.3.1': ['Leg day never', 'hl', 12, 2],
  'FOOTER.3.2': ['follow loafmaxi', 'orange b', 9, 1],
  'FOOTER.3.3': ['my soundcloud (please)', 'muted', 9, 1],
  'FOOTER.4.1': ['$NAPCOIN', 'hl b', 4, 2],
  'FOOTER.4.2': ['Built in a weekend', 'hl', 6, 1],
  'FOOTER.5.1': ['Panic Buy Partners', 'purple b', 2, 1],
  'FOOTER.5.2': ['how do i edit this', 'pink i u', 13, 1],
};
